apiVersion: dev.franck.com/v1alpha1
kind: VirtualEnvironment
metadata:
  name: dev2-env
  labels:
      name: crossplane-poc-dev2
spec:
  argocd:
    name: argo-cd
    version: 6.7.11
    repository: https://argoproj.github.io/argo-helm
    skipCreateNamespace: false
    values:
      server:
        services:
          type: LoadBalancer
      configs:
        cm:
          users.anonymous.enabled: false
          admin.enabled: true
        secret:
          argocdServerAdminPassword: $2a$10$UJbAlpup2UISMUpBPmK2iu0P1560uiHcnoI31/y9t4LnVSqPX5EOC # admin1234
        repositories:
          crossplane-poc:
            url: https://github.com/franck-art/crossplane-project.git
            name: crossplane-project
            type: git
            branch: main
            username: "franck-art"
            password: "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"

      extraObjects:
        - apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: vcluster-nginx-dev2
          spec:
            project: default
            source:
              repoURL: 'https://github.com/franck-art/crossplane-project.git'
              targetRevision: HEAD
              path: helm/tests-apps/nginx
            destination:
              server: 'https://kubernetes.default.svc'
              namespace: nginx
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
